/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import { _b } from '@ctx-core/object'
import type { nav_Ctx } from './nav_Ctx'
import type { nav_opened$_T } from './nav_opened$_b'
import { nav_opened$_b } from './nav_opened$_b'
export interface nav_ctx_I {
	nav_opened$?:nav_opened$_T
	nav_b_h?:nav_b_h_T
}
export interface nav_b_h_T {
	get nav_opened$():nav_opened$_T
}
export function nav_b_h_b(ctx:nav_Ctx):nav_b_h_T {
	return _b<nav_Ctx, 'nav_b_h'>('nav_b_h', ()=>{
		return {
			get nav_opened$() { return nav_opened$_b(ctx) }
		}
	})(ctx)
}