/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { nav_opened$_T } from './nav_opened$_b.js'
export interface nav_ctx_I {
	nav_opened$?:nav_opened$_T
}
